[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fintwit-web"
version = "0.1.0"
description = "Financial Twitter web application"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["app*"]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
profile = "black"

[tool.ruff]
line-length = 88
#select = ["I001"]

[tool.ruff.lint.pydocstyle]
# Use Google-style docstrings.
convention = "numpy"
