name: Run Ruff formatter

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check
      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check